export const TECH_LINKS = {
  AWS: "https://aws.amazon.com/",
  Bootstrap: "https://getbootstrap.com/",
  BootstrapVue: "https://bootstrap-vue.org/",
  CSS3: "https://www.w3.org/TR/css3-roadmap/",
  "Express.js": "https://expressjs.com/",
  Firebase: "https://firebase.google.com/",
  FormKit: "https://formkit.com/",
  GCP: "https://cloud.google.com/",
  GoldenLayout: "https://golden-layout.com/",
  HTML5: "https://html.spec.whatwg.org/multipage/",
  JavaScript: "https://www.javascript.com/",
  "Material UI": "https://material-ui.com/",
  MongoDB: "https://www.mongodb.com/",
  Mongoose: "https://mongoosejs.com/",
  MySQL: "https://www.mysql.com/",
  "Next.js": "https://nextjs.org/",
  "Node.js": "https://nodejs.org/",
  "Nuxt.js": "https://nuxt.com/",
  NuxtAuth: "https://auth.sidebase.io/",
  PHP: "https://www.php.net/",
  Pinia: "https://pinia.vuejs.org/",
  PrimeVue: "https://primevue.org/",
  React: "https://reactjs.org/",
  "React Highcharts": "http://kirjs.github.io/react-highcharts/",
  "React Hook Form": "https://react-hook-form.com/",
  "React Query": "https://react-query-v3.tanstack.com/",
  Recoil: "https://recoiljs.org/",
  "Redux Saga": "https://redux-saga.js.org/",
  SASS: "https://sass-lang.com/",
  "Sendbird Chat SDK":
    "https://sendbird.com/docs/chat/sdk/v4/javascript/overview",
  "Strapi CMS": "https://strapi.io/",
  "Tailwind CSS": "https://tailwindcss.com/",
  TypeScript: "https://www.typescriptlang.org/",
  "Vue.js": "https://vuejs.org/",
} as const;
