import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import type { RegistryItem } from "shadcn/schema";

const REGISTRY_PATH = resolve(process.cwd(), "registry");
const INDEX_PATH = resolve(REGISTRY_PATH, "__index__.tsx");

const HEADER = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";`;

const getComponentLoader = (item: RegistryItem) => {
  const mainFile = item.files?.find((f) => f.type === "registry:component");
  if (!mainFile) {
    return "undefined";
  }

  const importPath = `@/${mainFile.path.replace(/\.tsx?$/u, "")}`;
  const exportName = item.name;

  return `React.lazy(async () => {
      const mod = await import("${importPath}");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === "function" || typeof mod[key] === "object") || "${exportName}";
      return { default: mod.default || mod[exportName] };
    })`;
};

const buildIndex = async () => {
  const registryModule = await import(`file://${REGISTRY_PATH}/index.ts`);
  const { registry } = registryModule;

  const entries: string[] = [];

  for (const item of registry.items) {
    const files = item.files
      ?.map((f: { path: string; type: string; target?: string }) => {
        const entry = `path: "${f.path}", type: "${f.type}"`;
        const target = f.target ? `, target: "${f.target}"` : "";
        return `      { ${entry}${target} }`;
      })
      .join(",\n");

    const component = getComponentLoader(item);

    entries.push(`  "${item.name}": {
    name: "${item.name}",
    description: ${JSON.stringify(item.description || "")},
    type: "${item.type}",
    files: [${files ? `\n${files}\n    ` : ""}],
    component: ${component},
    categories: ${JSON.stringify(item.categories || null)},
    meta: ${JSON.stringify(item.meta || null)},
  }`);
  }

  const content = `${HEADER}

export const Index: Record<string, any> = {
${entries.join(",\n")},
};
`;

  writeFileSync(INDEX_PATH, content, "utf-8");
  console.log(
    `✅ Generated registry/__index__.tsx (${registry.items.length} items)`
  );
};

buildIndex();
